FROM ubuntu:latest

RUN     apt-get update && \
        apt-get upgrade -y && \
        apt-get install -y ruby build-essential libmagic-dev zlib1g-dev && \
	    apt-get install -y bundler
	
	RUN mkdir -p /opt/ubuntu_walker
        WORKDIR /opt/ubuntu_walker

	COPY . /opt/ubuntu_walker

	RUN bundle install 	

    CMD ["ruby","/opt/ubuntu_walker/runner.rb","-d","/tmp/dump","-r","redis://redis.icasl"]